import sys


# Define the HTML content
html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My HTML Page</title>
</head>
<body>
    <h1>periodic_table Page</h1>
    <p>This is a simple HTML page generated by Python.</p>
</body>
</html>
"""

# Open a file in write mode
with open("periodic_table.html", "w") as file:
    # Write the HTML content to the file
    file.write(html_content)

print("HTML page generated successfully!")
